/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.clase;
import javax.swing.JOptionPane;
/**
 *
 * @author liborio
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    int l;
    String Contraseña;

    public Principal() {
        initComponents();
        cmdIngresar.setEnabled(true);
        cmdTipoS.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdCambiar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmdIngresar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdCambiar = new javax.swing.JButton();
        txtMContra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDContra = new javax.swing.JPasswordField();
        cmdTipoS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Digite Su Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        cmdCambiar.setText("Cambiar");
        cmdCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        txtMContra.setEditable(false);
        txtMContra.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtMContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 160, 60));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));
        jPanel1.add(txtDContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, -1));

        cmdTipoS.setText("TIpo De Seguridad");
        cmdTipoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTipoSActionPerformed(evt);
            }
        });
        jPanel1.add(cmdTipoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 265));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed

        clase C;
        if (txtDContra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Su Contraseña", "Error", JOptionPane.ERROR_MESSAGE);
            txtDContra.requestFocusInWindow();
        } else {
            Contraseña = txtDContra.getText();
            l = Contraseña.length();
            C = new clase(l, Contraseña);
            JOptionPane.showMessageDialog(this, "Su Contraseña Ha Sido Guardada Correctamente");

            cmdIngresar.setEnabled(false);
            cmdMostrar.setEnabled(false);
            cmdCambiar.setEnabled(false);
            cmdTipoS.setEnabled(true);
            txtDContra.setEditable(false);
        }
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed

        String A;
        txtMContra.setText("");
        A = txtDContra.getText();
        txtMContra.setText(A);

        cmdIngresar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdCambiar.setEnabled(true);
        cmdTipoS.setEnabled(false);
        txtDContra.requestFocusInWindow();
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarActionPerformed

        int Oper;
        Long Contraseña = null;

        Oper = JOptionPane.showConfirmDialog(this, "¿Seguro Que Desea Cambiar Su Contraseña?", "Preguntar", JOptionPane.YES_NO_OPTION);
        if (Oper == JOptionPane.YES_OPTION) {
            txtDContra.setText("");
            txtMContra.setText("");
            txtDContra.requestFocusInWindow();
        }
        cmdIngresar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdCambiar.setEnabled(false);
        txtDContra.setEnabled(true);
        txtDContra.setEditable(true);
    }//GEN-LAST:event_cmdCambiarActionPerformed

    private void cmdTipoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTipoSActionPerformed

        String Contra;
        clase C;
        Contraseña = txtDContra.getText();
        l = Contraseña.length();
        C = new clase(l, Contraseña);
        Contra = C.Fuerte();
        txtMContra.setText(Contra);

        cmdIngresar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdCambiar.setEnabled(false);
        cmdTipoS.setEnabled(false);
    }//GEN-LAST:event_cmdTipoSActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCambiar;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdTipoS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtDContra;
    private javax.swing.JTextField txtMContra;
    // End of variables declaration//GEN-END:variables
}
